FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
    ansible \
    python3 \
    python3-pip \
    docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins