name: staging

services:
  backend:
    container_name: rpmarketplace-compose-staging-backend
    ports: !override
      - "5001:5000"

  frontend:
    container_name: rpmarketplace-compose-staging-frontend
    ports: !override
      - "8081:80"

networks:
  app-network:
    name: staging-network
    driver: bridge
